### ISSUE TITLE
Error when using OpenWeatherMap.org

### ISSUE THREAD

**Issue by nickshanks347** [codefenix-ConChaos/WxCenter#1]
When using OpenWeatherMap.org, i.e. a non-US city, I get the error:

```
!JavaScript wxcenter.js line 229: TypeError: wxObj[0] is undefined 
```

I have generated a free API key on OpenWeatherMap.org and added this to `wxcenter.ini`.

**Comment by codefenix-ConChaos** [comment]
The line number with the error tries to log a message indicating which source (Weather.gov or OpenWeatherMap.org) and location the forecast data is for. Normally we're guaranteed at least one result in the wxObj json object, which is why I have it trying to grab the first object with [0], but apparently that isn't the case here, therefore it's creating the error you're seeing. So I commented out that line in order to prevent that error from happening. 

However, the fact that you got that error in the first place most likely means the result set is empty. Because of that, it sounds like your API call to OpenWeatherMap is failing. Wouldn't hurt to double check your API key is correct.

If you try again with the latest version of wxcenter.js, you should now see a different outcome. Also watch your Synchronet Event log tab, as it should now log some additional debugging info that might help point to the root of the issue.

Some questions:

- Which non-US location are you trying? I'd like to try the same location myself and attempt to recreate your problem on my side.
- Are you using Linux or Windows?
- Which version of Synchronet?
- Does the script work for you if you try a US location (Weather.gov)?

**Comment by nickshanks347** [comment]
I actually think the OWM API was down yesterday, because now it works properly. It was either down, or one hour wasn't enough time for the servers to recognise my new API key. I've just tried it this morning and it works absolutely fine for non-US cities. Thank you for your quick reply and additional debugging, much appreciated!

**Comment by codefenix-ConChaos** [comment]
Glad to hear it's working for you now. I think the changes yesterday will be good to have in place for temporary outages like the one we seemingly had yesterday, so thanks for reporting the issue so it could get addressed.
